# Generated by Django 3.0.5 on 2020-04-07 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=100, null=True)),
                ('isImportant', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('form', models.TextField(null=True)),
                ('subject', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('isRead', models.BooleanField(default=False)),
            ],
        ),
    ]
